language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.12'
  - stable

env:
  global:
    - secure: CxEg2hSOUgwATFFAbD5ycalZdVvaKSTGIVyVYGze7NCqNaDhaXr1VSfrdfu+GrPp6+cYPhBB8Rr0LaweyZPqiVEHFWBtUiOjl5PShOazyiCNTX6ZQUCTHYQVkoIyKYhP/WVzmy6MfhCnuSkA129EeQ6dVUr/8NlIW2/N8PgU018=
    - GH_OWNER: zckrs
    - GH_PROJECT_NAME: gulp-angular-boilerplate

cache:
  directories:
    - node_modules
    - test/tmp/deps/node_modules

matrix:
  fast_finish: true

install:
  # Check the size of caches
  - du -sh ./node_modules ./test/tmp/deps/node_modules || true
  - npm install -g npm@latest
  # Instal npm dependecies and ensure that npm cache is not stale
  - ./scripts/generator-install-dependencies.sh

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gem install sass
  - npm install -g bower
  - npm install -g gulp

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run deploy
